#Code generated by Emmanuel Montes Lugo
#Date: 06/02/2022
#Use calc function

print("Welcome to Calculator for the ship")
first_number = input("firts  number is: ")
second_number = input("second number is: ")
print(int(first_number) + int(second_number))
