#Code generated by Emmanuel Montes Lugo
#Date: 06/02/2022
#Practice with variables

parsec = 11
#Unit converter formula is: 1 parsec equal to 3.26156 lightyears  
lightyears = 3.26156 * parsec
print(str(parsec) + " parsec, is " + str(lightyears) + " lightyears")